services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app

  frontend:
    image: python:3.12-slim
    working_dir: /site
    volumes:
      - ./frontend:/site
    command: python -m http.server 5500
    ports:
      - "5500:5500"
